version: '3'
networks:
  golangservicel0:
    external: false
services:
  nats-1:
    image: nats-streaming:latest
    ports:
      - 4222:4222
    networks:
      - golangservicel0
    volumes:
      - /var/lib/nats/nats-1/data:/data/stan/store
      - ./stan.conf:/etc/stan-config/stan.conf
    command: -sc /etc/stan-config/stan.conf
  nats-2:
    image: nats-streaming:latest
    ports:
      - 4223:4222
    networks:
      - golangservicel0
    volumes:
      - /var/lib/nats/nats-2/data:/data/stan/store
      - ./stan.conf:/etc/stan-config/stan.conf
    command: -sc /etc/stan-config/stan.conf